compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_config_file: "./glancewam/config/deepspeed/ds_config_zero0.json"
  deepspeed_multinode_launcher: standard
  deepspeed_dist_backend: nccl
  zero3_init_flag: false
distributed_type: DEEPSPEED
num_machines: 1
num_processes: 1
